name: Deploy to Cloudflare Pages

on:
  push:
    tags:
      - 'production-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Verify that Deploy Hook secret exists
        run: |
          if [ -z "${{ secrets.CF_DEPLOY_HOOK_URL }}" ]; then
            echo "❌ Secret CF_DEPLOY_HOOK_URL is not set!"
            exit 1
          else
            echo "✅ Secret CF_DEPLOY_HOOK_URL is set"
          fi

      - name: Trigger Cloudflare Pages deploy
        run: |
          echo "🚀 Triggering Cloudflare Pages deployment..."
          curl -X POST "${{ secrets.CF_DEPLOY_HOOK_URL }}"
          echo "✅ Deploy hook triggered successfully"
